language: haxe

haxe:
  - development
  - "3.4.2"
  - "3.2.1"

matrix:
  allow_failures:
    - haxe: development

os:
  - linux
  - osx

dist: trusty
sudo: false

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      export HXPROCESSING_PLATFORM=linux-amd64;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      export HXPROCESSING_PLATFORM=macosx-universal;
    fi

install:
  - haxelib install hxjava
  - haxelib install feffects
  - haxelib dev hxProcessing .
  - haxelib list

script:
  - haxe -D HXPROCESSING_PLATFORM=${HXPROCESSING_PLATFORM} empty.hxml && java -jar bin/Empty.jar
  - haxe -D HXPROCESSING_PLATFORM=${HXPROCESSING_PLATFORM} demo1.hxml
  - haxe -D HXPROCESSING_PLATFORM=${HXPROCESSING_PLATFORM} demo2.hxml