language: haxe

haxe:
  - development
  - "3.2.0"

matrix:
  allow_failures:
    - haxe: development

sudo: false

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - haxelib install empty.hxml --always
  - haxelib install demo1.hxml --always
  - haxelib install demo2.hxml --always

script:
  - haxe processing-linux64.hxml empty.hxml && java -jar bin/Empty.jar
  - haxe processing-linux64.hxml demo1.hxml
  - haxe processing-linux64.hxml demo2.hxml