language: haxe

haxe:
  - development
  - "3.2.1"

matrix:
  allow_failures:
    - haxe: development

os:
  - linux
  - osx

sudo: false

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      export HXP_PLATFORM=linux64;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      export HXP_PLATFORM=mac;
    fi

install:
  - haxelib install hxjava
  - haxelib install feffects
  - haxelib list

script:
  - haxe "processing-${HXP_PLATFORM}.hxml" empty.hxml && java -jar bin/Empty.jar
  - haxe "processing-${HXP_PLATFORM}.hxml" demo1.hxml
  - haxe "processing-${HXP_PLATFORM}.hxml" demo2.hxml