version: "{build}"

environment:
    global:
        HAXELIB_ROOT: C:\projects\haxelib
        HXP_PLATFORM: windows-amd64

install:
    - cinst haxe --version 3.4.2 -y
    - RefreshEnv
    - mkdir "%HAXELIB_ROOT%"
    - haxelib setup "%HAXELIB_ROOT%"
    - haxelib install hxjava   > log.txt || type log.txt && cmd /C exit 1
    - haxelib install feffects > log.txt || type log.txt && cmd /C exit 1
    - haxelib list

build: off

test_script:
  - haxe "processing-%HXP_PLATFORM%.hxml" empty.hxml && java -jar bin/Empty.jar
  - haxe "processing-%HXP_PLATFORM%.hxml" demo1.hxml
  - haxe "processing-%HXP_PLATFORM%.hxml" demo2.hxml